### PR TITLE
Add localization & Fix

### PR DESCRIPTION
**Pull request by Dierney**
We have specialized tools so we can make it quickly

### CODE REVIEW

**Comment by Dierney** [comment]
I don't think the added language should be converted to .lang file.
Because .lang files don't support all.

**Comment by gardenappl** [comment]
Could you send me a link to the tool? Or is it Chinese-only?

**Comment by Dierney** [comment]
Of course. It's completely open source.
No Chinese-only, but it's only has Chinese language and imperfect.
https://github.com/Shimogawa/Cs2Lang

**Comment by gardenappl** [comment]
The tool is interesting, but long-term I think I'd like to convert to .lang.

The en-US.lang file you provided is a good start, but some things are missing, like the Laputa Staff chat messages. I can add that in myself, though.

Do you think the Chinese translation is ready?

**Comment by Dierney** [comment]
yup, I have long been ready.
It's not that I don't want to add them. It doesn't support.
It currently only supports ItemName, ItemTooltip, BuffName, BuffDescription, ProjectileName, NPCName, MapObject, and Prefix.

[zh-Hans.zip](https://github.com/goldenapple3/Miscellania/files/2173820/zh-Hans.zip)

**Pull request merged**
